spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "1.0"

accounts:
  message: "ABC Bank accounts related local APIs"
  contactDetails:
    name: "John Prod - Developer"
    email: "johnprod@abcbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-6758