server:
  port: 8071
spring:
  application:
    name: "configserver"
  profiles:
    active: native
    #active: git
  cloud:
    config:
      server:
        native:
          # search-locations: "classpath:/config"
          search-locations: "file:///Users//silpaaleti//Downloads//msbytes//config"
      rabbitmq:
        host: "localhost"
        port: 5672
        username: "guest"
        password: "guest"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
encrypt:
  key: 2654534564657889
