spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          #search-locations: "classpath:/config"
          # search-locations: "file:///Users//silpaaleti//Downloads//msbytes//config"
        git:
          uri: https://github.com/aplis1/msbytes-config.git
          default-label: develop
          time-out: 5
          clone-on-start: true
          force-pull: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
encrypt:
  key: 2654534564657889

server:
  port: 8071
